package io.github.panjung99.routify.core.model.entity;

import io.github.panjung99.routify.core.model.enums.UnitEnum;
import lombok.Data;

import java.math.BigDecimal;

/**
 * Pricing Item entity representing the cost structure for model usage.
 * Defines pricing for input and output tokens/units with different rates.
 */
@Data
public class PricingItem {

    /**
     * Billing unit for this pricing item.
     * Common units include: mtokens (millions of tokens), nums (number of requests)
     */
    private UnitEnum unit;

    /**
     * Price per unit for input tokens/requests.
     * This is the cost for the data sent to the model.
     */
    private BigDecimal priceInput;

    /**
     * Price per unit for output tokens/requests.
     * This is the cost for the data generated by the model.
     */
    private BigDecimal priceOutput;
}
